/**
 * Type definitions for multi-agent system state management
 * All interfaces use strict TypeScript typing
 */

/**
 * Agent execution status
 */
export type AgentStatus = 'idle' | 'active' | 'blocked' | 'failed';

/**
 * Task complexity classification
 */
export type TaskComplexity = 'simple' | 'complex';

/**
 * Code review verdict
 */
export type ReviewVerdict = 'approved' | 'needs_repair' | 'rejected';

/**
 * System health status
 */
export type SystemHealth = 'healthy' | 'degraded' | 'failed';

/**
 * File change event types
 */
export type FileEventType = 'created' | 'modified' | 'deleted';

/**
 * Current system state - single source of truth
 * Written atomically by StateManager
 */
export interface SessionState {
  current_task: string | null;
  assigned_agent: string | null;
  complexity: TaskComplexity | null;
  architectural_design: Record<string, any>;
  dependency_report: Record<string, any>;
  review_verdict: ReviewVerdict | null;
  repair_attempts: number;
  generated_files: string[];
  last_updated: string; // ISO 8601 timestamp
  agent_status: Record<string, AgentStatus>;
}

/**
 * Session persistence data
 * Written on shutdown, read on startup
 */
export interface SessionSummary {
  session_id: string;
  start_time: string; // ISO 8601 timestamp
  end_time: string | null; // ISO 8601 timestamp
  accomplished: string[];
  next_steps: string[];
  incomplete_tasks: string[];
  system_health: SystemHealth;
}

/**
 * Agent activity log entry
 * Appended to conversation logs
 */
export interface AgentActivity {
  timestamp: string; // ISO 8601 timestamp
  agent: string;
  action: string;
  input: any;
  output: any;
  duration_ms: number;
}

/**
 * Failure event for circuit breaker tracking
 * Appended to failure_events.jsonl
 */
export interface FailureEvent {
  timestamp: string; // ISO 8601 timestamp
  agent: string;
  error: string;
  task: string;
  retry_count: number;
}

/**
 * Code repair event
 * Appended to applied_fixes.jsonl
 */
export interface FixEvent {
  timestamp: string; // ISO 8601 timestamp
  agent: 'repair-agent';
  original_issue: string;
  fix_applied: string;
  files_modified: string[];
  review_verdict: ReviewVerdict;
  attempt_number: number;
}

/**
 * Generated file metadata
 * Tracks files created/modified during execution
 */
export interface GeneratedFile {
  path: string;
  content: string;
  operation: 'create' | 'update';
  timestamp: string; // ISO 8601 timestamp
}

/**
 * Result from execution agents (Claude/Ollama)
 */
export interface ExecutionResult {
  success: boolean;
  output: string;
  error?: string;
  duration_ms: number;
  generatedFiles?: GeneratedFile[];
  targetPath?: string;
}

/**
 * Complete pipeline execution result
 * Returned by Pipeline.executeTask()
 */
export interface PipelineResult {
  success: boolean;
  task: string;
  complexity: string;
  assignedAgent: string;
  output: string;
  error?: string;
  totalDuration: number;
  architecturalGuidance?: {
    projectType: string;
    recommendedPaths: number;
    style: string;
  };
  review?: {
    verdict: string;
    issues: number;
    summary: string;
  };
  filesWritten?: string[];
  repairAttempts?: number;
}

/**
 * Filesystem change event
 * Generated by Watcher agent
 */
export interface FileChangeEvent {
  timestamp: string; // ISO 8601 timestamp
  path: string;
  event_type: FileEventType;
  detected_by: 'watcher';
}

/**
 * Log filter for querying conversation logs
 */
export interface LogFilter {
  agent?: string;
  start_date?: string; // ISO 8601 timestamp
  end_date?: string; // ISO 8601 timestamp
  error_type?: string;
}

/**
 * Code review result from Critic agent
 */
export interface CodeReview {
  verdict: ReviewVerdict;
  issues: CodeIssue[];
  summary: string;
  recommendations: string[];
  securityConcerns: SecurityConcern[];
  performanceIssues: PerformanceIssue[];
  reviewed_at: string; // ISO 8601 timestamp
}

/**
 * Code issue identified by Critic
 */
export interface CodeIssue {
  severity: 'critical' | 'high' | 'medium' | 'low';
  category: 'logic' | 'style' | 'security' | 'performance' | 'maintainability';
  description: string;
  location?: string;
  suggestedFix?: string;
}

/**
 * Security concern identified by Critic
 */
export interface SecurityConcern {
  type: string; // 'injection', 'xss', 'auth', 'crypto', etc.
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  recommendation: string;
}

/**
 * Performance issue identified by Critic
 */
export interface PerformanceIssue {
  type: string; // 'n+1', 'memory-leak', 'blocking', etc.
  description: string;
  impact: 'high' | 'medium' | 'low';
  suggestion: string;
}

/**
 * Code diff for review
 */
export interface CodeDiff {
  file: string;
  additions: string[];
  deletions: string[];
  context: string;
}

/**
 * Complexity analysis result from Router
 */
export interface ComplexityAnalysis {
  complexity: TaskComplexity;
  score: number; // 0-100
  factors: string[];
}

/**
 * Default/initial session state
 */
export const DEFAULT_SESSION_STATE: SessionState = {
  current_task: null,
  assigned_agent: null,
  complexity: null,
  architectural_design: {},
  dependency_report: {},
  review_verdict: null,
  repair_attempts: 0,
  generated_files: [],
  last_updated: new Date().toISOString(),
  agent_status: {},
};
